App/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

# SET THE NAMESPACE!
app_name = 'App'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('tela_exemplo/<int:id>', views.tela_exemplo, name='tela_exemplo'),
    path('index', views.index, name="index"),
    path('home', views.home, name="home"),
    path('graphs/', views.graphs, name="graphs"),
    path('get/ajax/pins',views.get_pins, name="get_pins"),
    path('graphs/get_data',views.get_data, name="get_data"),
    path('send_email',views.send_email, name="send_email"),
]

covidWeb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url,include
from App import views
from App.tasks import listener
from datetime import datetime

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.user_login,name='user_login'),
    path('App/',include('App.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('home', views.home, name="home"),
    path('graphs/', views.graphs, name="graphs"),
    path('get/ajax/pins',views.get_pins, name="get_pins"),
    path('graphs/get_data',views.get_data, name="get_data"),
    path('send_email',views.send_email, name="send_email"),
]

#listener(repeat=24*3600, repeat_until=None)

App/templates/graficos.html
{% extends "base.html" %}
{% block body_block %}
    <graficos-vue></graficos-vue>
{% endblock %}

App/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
    <v-container fluid class="primary d-flex flex-column justify-center align-center" fill-height :style="{fontFamily: 'Barlow, Helvetica, Arial, sans-serif',textAlign: 'center'}">
        <v-card raised color="secondary" max-width="405px" max-height="700px" width="400px" fluid class="d-flex px-0 " :style="{paddingTop: '35px',borderRadius: '10px'}" >
            <v-row class="mx-12 d-block"  justify="center" no-gutters > 
                <p class="text-center font-weight-bold  mt-10" :style="{fontSize: '60px',color: '#1E9CF8'}" >
                    <img style="height: 85px;" src='../static/logo/logoSGIS.png'/>
                </p> <!-- // ! Replacement for logo  -->
                
                <v-alert 
                    v-if="{{ login_error|safe }} == true" 
                    type="error"
                    dense
                    outlined
                >
                    Usuário ou senha inválidos
                </v-alert>

                <v-form
                    ref="form"
                    lazy-validation
                    method="POST"
                    v-bind:style="{paddingTop: '10px'}"
                    class="mt-8"
                > {% csrf_token %}
                    <v-text-field 
                        required 
                        label="Usuário ou Email"
                        name="username"
                        
                    ></v-text-field> 
                    <!-- // TODO detail more -->

                    <v-text-field
                        required 
                        label="Senha"
                        name="password"
                       
                        type="password"
                        
                    ></v-text-field> 

                    <script src='https://www.google.com/recaptcha/api.js'></script>
                    <div light class="g-recaptcha" data-sitekey="6LcTWegUAAAAAHjPv-dXhkJcOPmLy-EJfbJEUhim"></div>

                    <v-btn
                        color="primary"
                        class="mt-8 mb-0"
                        flat
                        height="50px"
                        width="100%"
                        type="submit"
                    >
                        Entrar
                        <!-- // TODO fix alignment -->
                    </v-btn>
                    
                    <v-btn href="{% url 'App:register' %}" text class="mt-2 sub-botao d-block; " style="font-size:medium !important;" width="100%" >Cadastrar</v-btn>
                    <v-btn text class="mt-1 sub-botao d-block mb-4" style="font-size:medium !important;" width="100%" >Esqueci minha senha</v-btn>
                </v-form>
            </v-row>
        </v-card>
    </v-container>
{% endblock %}

{% comment %} <v-card>
    <v-card-title>Login</v-card-title>
    <v-form
        ref="form"
        v-model="valid"
        lazy-validation
        method="POST"
    >
    {% csrf_token %}

        <v-text-field
            label="Login"
            required
            name="username"
        ></v-text-field>

        <v-text-field
            label="Senha"
            required
            name="password"
            :type="'password'"
        ></v-text-field>

        <v-btn>
            <input type="submit" name="" value="Entrar">
        </v-btn>
    </v-form>
</v-card> {% endcomment %}

App/templates/registration.html
{% extends "base.html" %}
{% block body_block %}
<v-container fluid class="primary d-flex flex-column justify-center align-center" fill-height :style="{fontFamily: 'Barlow, Helvetica, Arial, sans-serif',textAlign: 'center'}">
    <v-card raised color="secondary" max-width="405px" max-height="700px" width="400px" fluid class="d-flex px-0 " :style="{paddingTop: '35px',borderRadius: '10px'}" >
        <v-row class="mx-12 d-block"  justify="center" no-gutters > 
            <p class="text-center font-weight-bold mt-4" :style="{fontSize: '60px',color: '#1E9CF8'}" >
                <img style="height: 85px;" src='https://i.ibb.co/TRs2mSc/logoSGIS.png'/>
            </p> 
            <v-card-title class="justify-center font-weight-bold mt-0 pt-0">Registre-se aqui</v-card-title>
            <v-card-subtitle>Preencha o formulário.</v-card-subtitle>
            <v-alert 
                v-if="{{ register_error|safe }} == true" 
                type="error"
                dense
                outlined
            >
                Falha no cadastro
            </v-alert>
                
            <v-form
                ref="form"
                lazy-validation
                method="POST"
                v-bind:style="{paddingTop: '10px'}"
            > {% csrf_token %}
        
                <v-text-field 
                    required 
                    label="Usuário"
                    name="username"
                ></v-text-field> 
                <v-text-field
                    required 
                    label="Senha"
                    name="password"
                    type="password"
                ></v-text-field> 
                <v-text-field
                    label="Email"
                    required
                    name="email"
                ></v-text-field>
                <!--<v-text-field
                    label="Chave de Acesso"
                    required
                    name="id"
                ></v-text-field>-->
                <v-text-field
                    label="Instituição"
                    required
                    name="instituicao"
                ></v-text-field>

                <script src='https://www.google.com/recaptcha/api.js'></script>
                <div class="g-recaptcha" data-sitekey="6LcTWegUAAAAAHjPv-dXhkJcOPmLy-EJfbJEUhim"></div>

                <v-btn
                    color="primary"
                    class="mt-2 mb-8"
                    flat
                    height="50px"
                    width="100%"
                    type="submit"
                >
                    Registrar
                </v-btn>
                
            </v-form>
        </v-row>
    </v-card>
</v-container>
{% endblock %}

App/templates/vue_list.html
<html>
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>
  <div id="app">
    <v-app>
      <!-- --------TAB BAR--------->
      <template>
        <div>
          <v-app-bar
            color="#1E9CF8"
            dense
            dark
            flat
          >
            <v-app-bar-nav-icon></v-app-bar-nav-icon>
            
            <v-toolbar-title>XÔ COVID</v-toolbar-title>
      
            <v-spacer></v-spacer>
      
            <v-menu
              left
              bottom
            >
              <template v-slot:activator="{ on }">
                <v-btn icon v-on="on">
                  <v-icon>mdi-dots-vertical</v-icon>
                </v-btn>
              </template>
      
              <v-list>
                <v-list-item
                  v-for="n in 5"
                  :key="n"
                  @click="() => {}"
                >
                  <v-list-item-title>Option {{ n }}</v-list-item-title>
                </v-list-item>
              </v-list>
            </v-menu>
          </v-app-bar>
        </div>
      </template>
      <!-- --------CARD MENU--------->
      <div class="text-center" style="position: absolute;bottom: 30px;right: 110px;left: 110px;">
        <template>
        <v-bottom-navigation
          grow
          height="100"
          background-color="white"
          color="#1E9CF8"
        >
          <v-btn>
            <span style="color:#1E9CF8">Mais informações</span>
            <v-icon size="55" color="#1E9CF8">mdi-file</v-icon>
          </v-btn>
          <v-btn disabled style="background-color: white !important;" >
            <div class="text-center">
              <v-list-item-subtitle style="color:#1E9CF8">11/03/2020</v-list-item-subtitle>
            </div> 
          </v-btn>

          <v-btn>
            <span style="color:#1E9CF8">Voltar</span>
            <v-icon size="55" color="#1E9CF8">mdi-chevron-left-box</v-icon>
          </v-btn>
      
          <v-btn disabled style="background-color: white !important;" >
            <div class="text-center">
              <v-list-item-title style="color:#1E9CF8"><b>21/03/2020</b></v-list-item-title>
            </div> 
          </v-btn>
      
          <v-btn>
            <span style="color:#1E9CF8">Avançar</span>
            <v-icon size="55" color="#1E9CF8">mdi-chevron-right-box</v-icon>
          </v-btn>
          <v-btn disabled style="background-color: white !important;" >
            <div class="text-center">
              <v-list-item-subtitle style="color:#1E9CF8">31/03/2020</v-list-item-subtitle>
            </div> 
          </v-btn>
          
          <v-bottom-sheet v-model="sheet" >
            <template v-slot:activator="{ on }">
              <v-btn v-on='on'>
                <span style="color:#1E9CF8">Alterar base de dados</span>
                <div class="text-center">
                  <v-list-item-title style="color:#1E9CF8">Ministério da Saúde</v-list-item-title>
                </div>
              </v-btn>
            </template>
            <v-sheet class="text-center" height="200px">
              <!-- <v-btn
                class="mt-6"
                flat
                color="blue"
                @click="sheet = !sheet"
                v-on='o'
              >close</v-btn> -->
              <v-container>
                <v-row>
                  <v-col
                    cols="6"
                  >
                    <v-card
                      class="mx-auto"
                      elevation="2"
                      flat
                    >
                    <v-list-item three-line>
                      <v-list-item-content>
                        <!-- <div class="overline mb-2">OVERLINE</div> -->
                        <v-list-item>
                          <v-tooltip top color="#1E9CF8">
                            <template v-slot:activator="{ on }">
                              <v-btn v-on="on" icon><v-icon size="30" color="#1E9CF8">mdi-information-outline</v-icon></v-btn>
                            </template>
                            <span>A base de dados é de responsabilidade do Ministério da Saúde.</span>
                          </v-tooltip>
                        </v-list-item>

                        <v-list-item-title class="headline mb-1">Ministério da Saúde</v-list-item-title>   
                        <v-list-item-subtitle class="mb-2">Base de dados oficial disponibilizada pelo Ministério da Saúde</v-list-item-subtitle>
                    
                        <div class="justify-center">
                            <v-btn outlined color="#1E9CF8">
                              Selecionar
                            </v-btn>
                        </div>
                      </v-list-item-content>
                    </v-card>
                  </v-col>
                
                  <v-col
                    cols="6"
                  >
                      <v-card
                      class="mx-auto"
                      elevation="2"
                      flat
                    >
                    <v-list-item three-line>
                      <v-list-item-content>
                        <!-- <div class="overline mb-2">OVERLINE</div> -->
                        <v-list-item>
                          <v-tooltip top color="#1E9CF8">
                            <template v-slot:activator="{ on }">
                              <v-btn v-on="on" icon><v-icon size="30" color="#1E9CF8">mdi-information-outline</v-icon></v-btn>
                            </template>
                            <span>A base de dados é de responsabilidade do Ministério da Saúde.</span>
                          </v-tooltip>
                        </v-list-item>

                        <v-list-item-title class="headline mb-1">Base Colaborativa</v-list-item-title>   
                        <v-list-item-subtitle class="mb-2">Base de dados não oficial disponibilizada por usuários da plataforma</v-list-item-subtitle>
                    
                        <div class="justify-center">
                            <v-btn outlined color="#1E9CF8">
                              Selecionar
                            </v-btn>
                        </div>
                      </v-list-item-content>
                    </v-card>
                  </v-col>
                </v-row>
              </v-container>

            </v-sheet>
          </v-bottom-sheet>
          

          

        </v-bottom-navigation>
      </template>
    </div>
    <!-- --------CARD MENU 2--------->
    
    </v-app>
  </div>
  
  
</body>
<script>
    new Vue({
      el: '#app',
      vuetify: new Vuetify(),
    })
  </script>
  <script>
    export default {
      data: () => ({
        checkbox: true,
        sheet: false,
      }),
    }
</script>
</html>